ENTRY(_start)
SECTIONS
{
    . = 1M;
   .boot :
    {
        /* ensure that the multiboot header is at the beginning */
        *(.multiboot2_header)
    }

    .text : ALIGN(4096)
    {
        *(.text)
    }

    .asm : ALIGN(4096)
    {
        *(.asm)
    }

    .rodata : ALIGN(4096)
    {
        *(.rodata)
    }

    .data : ALIGN(4096)
    {
        *(.data)
    }

    .bss : ALIGN(4096)
    {
        *(COMMON)
        *(.bss)
    }
}
